version: "3.4"

# replace "ptb" with the short name of your project
# mongodb, public_bot and private_bot are service names. They should be unique in this project.
# ptb_mongodb, ptb_public_bot and ptb_private_bot are container names. They should be unique as well across projects.
# best practice is prefix them with the short name of your project.

# below we register three services
services:
    mongodb:
        container_name: ptb_mongodb
        image: mongo:4.4.21-focal
        restart: always
        expose:
            - ${MONGODB_PORT} # only allow inter-container communication
        volumes:
            - "./mongo/mongod.conf:/etc/mongod.conf"
            - "./storage/mongo:/data/db"

    # The receiving end
    public_bot:
        container_name: ptb_public_bot
        build: ./public-bot
        restart: always
        command: python3 src/main.py
        depends_on:
            - mongodb
        volumes:
            - "./storage/app/public:/myapp:rw" # container specific storage space
            - "./storage/app/shared:/shared:rw" # shared storage space
        deploy:
            mode: global
            resources:
                limits:
                    cpus: 1
                    memory: 1024M

    # The firing end
    private_bot:
        container_name: ptb_private_bot
        build: ./private_bot
        restart: always
        command: python3 src/main.py
        depends_on:
            - mongodb
            - public_bot
        volumes:
            - "./storage/app/private:/myapp:rw" # container specific storage space
            - "./storage/app/shared:/shared:rw" # shared storage space
        deploy:
            mode: global
            resources:
                limits:
                    cpus: 2
                    memory: 2048M
